
[Interface]
PrivateKey = OJO7WB/+Tv71PGjxTxPuc9/5WDg36Fkg7EkwZM7JUm0=
Address = 10.8.0.14/24
DNS = 1.1.1.1

[Peer]
PublicKey = bztmR8/SeaaBDSyc0j5gD9SVpgQM85zEaFSFbokkLhg=
PresharedKey = yoGsaE8xfWges1EduoEdXB/8URAc7Q1cH18IBOH1pNI=
AllowedIPs = 0.0.0.0/0, ::/0
PersistentKeepalive = 0
Endpoint = 131.221.0.131:51820